require 'rubygems'
require 'rake'
require 'rspec/core/rake_task'

ENV["env"] ||= 'staging'

############# ALL ############# 

# RUN ALL

desc "Run all tests"
RSpec::Core::RakeTask.new('all') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = [
      'spec/legacy/*.rb',
      'spec/oyster/media/*.rb',
      'spec/v2/*.rb',
      'spec/v3/**/*.rb',
      ]  
end

# RUN ALL FRONTEND 

desc "Run all frontend tests"
RSpec::Core::RakeTask.new('frontend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = [
      'spec/legacy/*.rb',
      'spec/oyster/media/*.rb',
      ]  
end

# RUN ALL BACKEND

desc "Run all backend tests"
RSpec::Core::RakeTask.new('backend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = [
      'spec/v2/**/*.rb',
      'spec/v3/video/*.rb'
      #'spec/v3/**/*.rb', uncomment this when v3 articles are ready, and del line above
      ]  
end

############# V3 ############# 

desc "Run v3 tests"
RSpec::Core::RakeTask.new('v3') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v3/video/*.rb'
    t.pattern = #'spec/v3/**/*.rb' uncomment this when v3 articles are ready, and del line above
end

desc "Run v3 video tests"
RSpec::Core::RakeTask.new('v3video') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v3/video/*.rb'    
end

desc "Run v3 articles tests"
RSpec::Core::RakeTask.new('v3articles') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v3/articles/*.rb'    
end

############# V2 ############# 

desc "Run v2 tests"
RSpec::Core::RakeTask.new('v2') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v2/**/*.rb'    
end

desc "Run v2 articles"
RSpec::Core::RakeTask.new('v2articles') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v2/articles.rb'    
end

desc "Run v2 blogs"
RSpec::Core::RakeTask.new('v2blogs') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v2/blogs.rb'    
end

############# OYSTER ############# 

desc "Run All Oyster FE Tests"
RSpec::Core::RakeTask.new('oysterfrontend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/oyster/media/*.rb'
end

############# TECH ############# 

desc "Run Tech Frontend and API tests"
RSpec::Core::RakeTask.new('techall') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = ['spec/oyster/media/tech.rb', 'spec/v2/tech.rb']  
end

desc "Run Tech frontend tests"
RSpec::Core::RakeTask.new('techfrontend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/oyster/media/tech.rb'  
end

desc "Run Tech API tests"
RSpec::Core::RakeTask.new('techapi') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v2/tech.rb'    
end

############# VIDEO ############# 

desc "Run Video tests"
RSpec::Core::RakeTask.new('videofrontend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = ['spec/oyster/media/video.rb']  
end

############# IMAGES ############# 

desc "Run Tech Frontend and API tests"
RSpec::Core::RakeTask.new('imagesfrontend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = ['spec/oyster/media/images.rb']  
end

############# LEGACY ############# 

desc "Run Legacy game hub tests"
RSpec::Core::RakeTask.new('legacyhubsfrontend') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = ['spec/legacy/legacy_hubs.rb']  
end

############# DEPRECATED / INVALID ############# 

desc "" 
RSpec::Core::RakeTask.new('oauth2') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/topaz/oauth2/**/*.rb'
end

desc "topaz - entitlement services"
RSpec::Core::RakeTask.new('entitlement_services') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/topaz/entitlement_services/**/*.rb'
end


desc "Run examples" 
RSpec::Core::RakeTask.new('examples') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/examples/**/*.rb'
end

desc "Run IGN stress test"
RSpec::Core::RakeTask.new('ignstress') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/ign-perf/**/*.rb'
end

desc "Run v1 tests"
RSpec::Core::RakeTask.new('v1') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/v1/**/*.rb'
end

desc "Run social tests"
RSpec::Core::RakeTask.new('social') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/social/**/*.rb'
end

desc "Run prime tests"
RSpec::Core::RakeTask.new('prime') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/prime/*.rb'
end

desc "Run Topaz tests"
RSpec::Core::RakeTask.new('authentication-services') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/topaz/ign-auth/topaz_*.rb'
end

desc "Run Topaz tests"
RSpec::Core::RakeTask.new('ign-auth') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/oyster/social/topaz_*.rb'
end

desc "Run social_api tests"
RSpec::Core::RakeTask.new('social_api') do |t|
    t.rspec_opts = ["-Ilib"]
    t.pattern = 'spec/social_api/**/*.rb'
end

desc "Run social_test tests"
RSpec::Core::RakeTask.new('social_test') do |t|
    t.rspec_opts = ["-Ilib"]
    t.pattern = 'spec/social_test/**/*.rb'
end

desc "Run follow user test"
RSpec::Core::RakeTask.new('status_oauth') do |t|
    t.rspec_opts = ["-Ilib","--format documentation","--color"]
    t.pattern = 'spec/social_api/status_oauth.rb'  
end
desc "Run gobID for v3 test"
RSpec::Core::RakeTask.new('v3_gobId') do |t|
  t.rspec_opts = ["-Ilib", "--format documentation","--color"]
  t.pattern = 'spec/v1/v3_gobId.rb'
end
