require 'rubygems'
require 'rake'
require 'rake/testtask'

Rake::TestTask.new do |t|
    t.libs << '../lib' << '../lib/helpers' << '../config'
    t.test_files = FileList['suites/**/checkout*.rb']
    t.verbose = true
end