development:
  baseurl: fklun.dev.s.ign.com
  annual_name: Prime - Annual
  annual_price: 49.95
  annual_autobill: Prime Annual
  2year_name: Prime 2 Year
  2year_price: 79.95
  2year_autobill: Prime 2 Year
  trial_name: Prime 30 Day Trial
  trial_price: 0.00
  trial_autobill: 30 Day Trial of IGN Prime
staging:
  baseurl: 

production:
  baseurl: s.ign.com
  
chrome:
  browser: Chrome
  
firefox:
  browser: Firefox
  
ie:
  browser: IE
 
headless:
  browser: Headless
