require 'rubygems'
require 'rake'
require 'rspec/core/rake_task'

#SELENIUM_RC_JAR = Dir[File.dirname(__FILE__) + "/server/selenium-server*.jar"].first

# Selenium::Rake::RemoteControlStartTask.new(:'rc:start') do |rc|
  # rc.port = 4444
  # rc.timeout_in_seconds = 60
  # rc.background = true
  # rc.wait_until_up_and_running = true
  # rc.jar_file = SELENIUM_RC_JAR
  # #rc.additional_args << "-firefoxProfileTemplate FirefoxPrimeUser"
# end
# 
# Selenium::Rake::RemoteControlStopTask.new(:'rc:stop') do |rc|
  # rc.host = "localhost"
  # rc.port = 4444
  # rc.timeout_in_seconds = 60
# end
# 
# # Restart selenium server task
# desc "Restart Selenium Remote Control"
# task :'rc:restart' do
 # Rake::Task[:"rc:stop"].execute [] rescue nil
 # Rake::Task[:"rc:start"].execute []
# end

# Rake::TestTask.new(:'run_test') do |t|
    # t.libs << 'lib' << 'lib/helpers' << 'config'
    # t.test_files = FileList['functional/suites/vindicia_checkout_chrome.rb']
    # t.verbose = true
# end

desc "Prime CC transactions"
RSpec::Core::RakeTask.new('prime_cc_tests') do |t|
	t.rspec_opts = ["-Ilib","--format h > output.html","--color"]
	t.pattern = 'functional/suites/checkout_cc.rb'    
end

desc "Prime login/registration"
RSpec::Core::RakeTask.new('prime_topaz_tests') do |t|
	t.rspec_opts = ["-Ilib","--format documentation","--color"]
	t.pattern = 'functional/suites/login_registration.rb'
end

desc "Prime account management"
RSpec::Core::RakeTask.new('prime_account_tests') do |t|
	t.rspec_opts = ["-Ilib","--format documentation","--color"]
	t.pattern = 'functional/suites/account_management.rb'    
end

desc "entitlements test"
RSpec::Core::RakeTask.new('entitlements') do |t|
	t.rspec_opts = ["-Ilib","--format documentation","--color"]
	t.pattern = 'functional/suites/entitlements.rb'    
end

desc "vindicia test"
RSpec::Core::RakeTask.new('vindicia_test') do |t|
  t.rspec_opts = ["-Ilib","--format documentation","--color"]
  t.pattern = 'functional/suites/vindicia_test.rb'
end
